version: "3"
services:
  web:
    build: .
    command: sh -c "uvicorn Api:app --reload --port=8000 --host=0.0.0.0"
    ports:
      - "8000:8000"
    volumes:
      - .:/app
volumes:
  config:
    external: true
